### ISSUE TITLE
Song-Command | laut.fm API

### ISSUE THREAD

**Issue by officialLucas** [VocalZero/discord-musicbot#1]
Guten Tag,

der Song-Befehl funktioniert in Verbindung mit der laut.fm-API nicht.
Ist dies ein bereits bekannter Fehler?

Mit freundlichen Grüßen
Lucas

**Comment by VocalZero** [comment]
Ist jetzt so bei mir nicht bekannt gewesen. Ich werde mal drüber schauen. Mit welchem Laut.FM Stream hast du es versucht und kannst du ein Log schicken vom Bot?

**Comment by officialLucas** [comment]
Guten Abend,

ich versuche es derzeit mit laut.fm/happyfm.
Welchen Log benötigst du und wo finde ich diesen?

Mit freundlichen Grüßen
Lucas

**Comment by VocalZero** [comment]
Ich brauche nur die Konsolen Ausgabe was der Bot bei dem Fehler ausgibt.

**Comment by officialLucas** [comment]
Es kommt kein Fehler in der Konsole, es wird nur keine Nachricht im Discord geschrieben.

**Comment by NurKai3** [comment]
Kann ich ebenso bestätigen, es kommen keine Fehler und es wird keine Nachricht ausgegeben, Alle Laut.FM Streamlinks funktionieren nicht.

**Comment by VocalZero** [comment]
![Screenshot 2020-10-28 183648](https://user-images.githubusercontent.com/20924469/97474609-913f8480-194c-11eb-81b9-3b5edc086e89.png)

Bei mir gehts mit einem Laut.FM Stream.
Kannst du es einmal mit einem nicht Laut.FM Stream versuchen?

**Comment by NurKai3** [comment]
https://stream.laut.fm/radiofire

**Comment by officialLucas** [comment]
Mit einem anderen Stream geht es bei mir auch nicht :(

**Comment by VocalZero** [comment]
@NurKai3 Dein Link (https://stream.laut.fm/radiofire) ist nur eine Weiterleitung versuch es mal mit https://radiofire.stream.laut.fm/radiofire

**Comment by VocalZero** [comment]
@officialLucas Du kannst es wie @NurKai3 mal versuchen dein Streamlink zu ändern auf https://happyfm.stream.laut.fm/happyfm

**Comment by officialLucas** [comment]
Es funktioniert, danke sehr :)

**Comment by VocalZero** [comment]
@officialLucas Freut mich das ich dir weiterhelfen konnte ;)

**Comment by NurKai3** [comment]
achsu, vielen Dank Kacper :3
